# Generated by Django 2.0.4 on 2018-04-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AquaticPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree_of_difficulty', models.IntegerField()),
                ('selling_volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LandscapePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='aquaticplant',
            name='general_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aquaticPlants.GeneralClassification'),
        ),
        migrations.AddField(
            model_name='aquaticplant',
            name='landscape_position',
            field=models.ManyToManyField(to='aquaticPlants.LandscapePosition'),
        ),
        migrations.AddField(
            model_name='aquaticplant',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='units.Unit'),
        ),
    ]
