# Generated by Django 2.0.4 on 2018-05-02 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productAquaticPlantPackages', '0001_initial'),
        ('stores', '0002_auto_20180501_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAPPEveluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_eveluations', to='productAquaticPlantPackages.ProductAquaticPlantPackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreEveluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_eveluations', to='stores.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
