# Generated by Django 2.0.4 on 2018-05-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        ('images', '0001_initial'),
        ('categories', '0001_initial'),
        ('aquaticPlants', '0002_aquaticplant_image'),
        ('stores', '0002_auto_20180501_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAquaticPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algae_level', models.IntegerField()),
                ('gastropoda_level', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('aquatic_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquaticPlants.AquaticPlant')),
                ('image', models.ManyToManyField(to='images.Image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAquaticPlantPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productAquaticPlantPackages', to='categories.Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.Store')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='units.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
