# Generated by Django 2.0.4 on 2018-05-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productAquaticPlantPackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaquaticplant',
            name='product_aquatic_plant_package',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='productAquaticPlantPackages.ProductAquaticPlantPackage'),
            preserve_default=False,
        ),
    ]
