# Generated by Django 2.0.4 on 2018-05-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productAquaticPlantPackages', '0003_auto_20180502_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaquaticplant',
            name='aquatic_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productAquaticPlants', to='aquaticPlants.AquaticPlant'),
        ),
        migrations.AlterField(
            model_name='productaquaticplantpackage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.Category'),
        ),
    ]
