# Generated by Django 2.0.4 on 2018-04-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('clicks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='images.ImageSource'),
        ),
    ]
